- api/app/applicationModel/api.py
- api/app/applicationModel/mixins.py
- api/app/applicationModel/models.py
- api/app/applicationModel/tests.py
- api/app/events/models.py
- api/app/responses/models.py
- api/app/routes.py
- api/app/utils/errors.py
I believe I covered everything. First time following a TDD approach, so please let me know if I missed anything.
P.S. screw python for needing the __init__.py file, even if its blank. That took me way too long to figure out.
> Added ApplicationForm controller get request to return app-form based on event_id

- api/app/applicationModel/models.py
- api/app/applicationModel/tests.py
- api/app/users/models.py
- api/app/utils/testing.py
Also fixed some issues this picked up
> Updated tests to use SQLLite in-memory database

- webapp/.env.test
> Added test api env url.

- api/app/responses/api.py
- api/app/tests/test_email.py
- api/app/utils/emailer.py
- api/app/utils/strings.py
- Added emailing functionality to the response api's post method
- Added a common strings file for statically defined strings
- Mocked out the emailer service in debug environments
Please review if I mocked the emailer service out correctly
> Response confirmation email

- webapp/package.json
- webapp/src/components/form/FormSelect.js
- webapp/src/components/form/FormTextArea.js
- webapp/src/components/form/FromTextBox.js
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/utils/validation/validationFields.js
Added descriptions to fields in create account screen through tool tips on their respective labels.
Issue #62
> Added descriptions to key validation fields as tool tips 

- api/app/responses/api.py
- webapp/package.json
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/services/applicationForm/applicationForm.service.js
> Withdraw frontend

- webapp/src/components/form/FormTextArea.js
- webapp/src/pages/applicationForm/Application.css
Removed console log messages and removed package-lock.json
> added word counter beside every Form Text Area & fixed 2 more issues

- webapp/src/App.js
- webapp/src/components/form/FormToolTip.js
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/pages/home/Home.css
- webapp/src/pages/home/Home.js
Implementation of https://github.com/deep-learning-indaba/Baobab/issues/116 and https://github.com/deep-learning-indaba/Baobab/issues/105.
> Minor ui enhancements

- api/app/events/api.py
- webapp/package.json
- webapp/src/index.js
- webapp/yarn.lock
Implementation of https://github.com/deep-learning-indaba/Baobab/issues/106 and https://github.com/deep-learning-indaba/Baobab/issues/123.
> IE polyfill and application not available when logged in bug

- api/app/files/api.py
- webapp/src/components/form/FormFileUpload.js
- webapp/src/pages/applicationForm/Application.css
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/services/file/file.service.js
- webapp/src/services/file/index.js
Implements front-end functionality for file upload in application form. 
Modified backend to conditionally not use credentials to test on GCP
Resolves #42
> File upload Frontend

- webapp/src/App.css
- webapp/src/App.js
- webapp/src/pages/applicationForm/Application.css
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/pages/home/Home.js
- webapp/src/pages/login/components/LoginForm.js
- webapp/src/pages/profile/components/ProfileForm.js
- webapp/src/pages/resetPassword/ResetPassword.css
- webapp/src/pages/resetPassword/components/ConfirmPasswordResetForm.js
- webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js
- webapp/src/pages/verifyEmail/VerifyEmail.css
- webapp/src/pages/verifyEmail/components/VerifyEmailComponent.js
- webapp/src/utils/styling/styling.js
- webapp/src/utils/validation/validationFields.js
- Updated loading indicators to Bootstrap 4 spinners
- Resolves #113 
- Resolves #119 
- Resolves #120 
- Resolves #143 
- Resolves #131
> Various UI/UX improvements

- webapp/src/pages/applicationForm/components/ApplicationForm.js
> Open award link in new tab

- api/app/routes.py
- api/app/users/api.py
- api/app/users/tests.py
@KaleabTessera Here is the backend for `resend_verification`. I'm likely going to make a hash of the frontend. Not sure where to put the button either. 
Thoughts?
> Resend verification email backend

- api/app/applicationModel/api.py
Before I carry on and make this a large PR, I'd like to get some feedback on the way I am approaching this. Everyone happy with the levels/exception handling?
> Logging-Phase 1

- webapp/src/App.css
- webapp/src/App.js
- webapp/src/components/ErrorPage.jsx
Also updated error page with pre-populated mailto link
Resolves: #161
> Added "report a bug" button

- api/migrations/versions/b4c1dfa70233_add_ethnicity_question.py
- webapp/src/App.css
> Add ethnicity question

- webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js
I think this will fix #169 - but let's leave that open until we confirm.
> Fixed typo preventing error from being displayed

- api/app/files/api.py
- api/app/responses/api.py
- webapp/src/components/form/FormFileUpload.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
> Update file upload and display of answer values

- api/app/users/api.py
- api/app/users/tests.py
Added user roles to authentication response
> User roles

- api/app/responses/models.py
- api/app/reviews/api.py
- api/app/reviews/tests.py
Resolves  https://github.com/deep-learning-indaba/Baobab/issues/181#issuecomment-477708758
> Display the label for answers to multi-choice questions

- api/app/content/api.py
- api/app/users/api.py
- webapp/src/services/user/user.service.js
Resolves issue #200 
P.S. While testing the new title, I noticed that the update user profile functionality was broken due to new fields being added to the db after the fact but not updated in the front end or the PUT API. So just fixed those now as well.
> Add Mx title and fix user profile update

- api/app/users/api.py
- api/app/users/models.py
- api/app/users/tests.py
> Revalidate email after changing email

- api/app/__init__.py
- webapp/src/pages/eventStats/EventStats.css
- webapp/src/pages/eventStats/components/EventStatsComponent.js
- webapp/src/services/eventStats/eventStats.service.js
- Mah first React PR. 
- Has a single button to send reminders to both unsubmitted and not started. Can't see the use case in separating the requests. 
- Excuse the roughness, still learning. let me know where I can improve :)
> Attempting to add a button to send reminders

- api/app/routes.py
- api/app/users/api.py
- api/app/users/mixins.py
- api/app/users/repository.py
- api/app/users/tests.py
Resolves first part of #242 
In terms of returning the application status, I simply returned the is_submitted, is_withdrawn, and the time stamp fields. Let me know if any processing should be done here to perhaps return a clean application status field with values like 'unsubmitted', 'submitted', and 'withdrawn'
> Add user profile list

- api/app/routes.py
- api/app/users/api.py
- api/app/users/models.py
- api/app/users/tests.py
> Added UserComment model, controller and tests

- api/app/reviews/api.py
- api/app/reviews/repository.py
- webapp/src/pages/reviewAssignment/components/ReviewAssignmentComponent.js
- Fixed bug where all reviewers were showing with same number of reviews assigned
- Fixed bug where a reviewer could be assigned to the same response more than once
> Fixes to Review assignment

- api/app/routes.py
- api/app/users/api.py
- api/app/users/mixins.py
- api/app/users/repository.py
- api/app/users/tests.py
Resolves the second part of #242 
Just a quick question around running tests, how do we run a specific test, class, or file? We have 100 tests now and it takes about 3 and half minutes on my machine to run them all. I want to run specific ones while I'm developing them to have a shorter feedback loop. I tried looking at the nosetests docs but the commands for running specific tests don't seem to work. I'm assuming the `docker-compose run web nosetests` is hooking into something else that is actually running the actual nosetest commands but I can't seem to find where that is (and this where I'm thinking the commands from the nosetest docs would actually work).
> Get user profile when system or event admin

- webapp/src/components/form/FormTextArea.js
> Fix state issue with text area

- webapp/src/pages/review/components/ReviewForm.js
Resolves #259 
And made it more obvious that department is field of study
> Added go back button 

- webapp/src/pages/home/Home.js
Updated homepage with clear application status for "complete your application" campaign.
> Updated homepage with clear application status

- webapp/src/App.js
- webapp/src/pages/profileList/ProfileList.css
- webapp/src/pages/profileList/ProfileList.js
- webapp/src/pages/profileList/__tests__/ProfileList.test.js
- webapp/src/pages/profileList/components/ProfileListComponent.js
- webapp/src/pages/profileList/index.js
- webapp/src/services/profilelist/index.js
- webapp/src/services/profilelist/profilelist.service.js
- webapp/src/services/reviews/index.js
- webapp/src/services/user/user.service.js
*Included nav-links in App.js to view profiles as system / event admin.
*ProfileServices, ProfileComponents and Tests for each as per project structure.
> Card ProfileList-Display:

- webapp/package.json
- webapp/src/App.js
- webapp/src/pages/profile/components/ProfileForm.js
- webapp/src/pages/profileList/ProfileList.css
- webapp/src/pages/profileList/components/ProfileListComponent.js
- webapp/src/pages/viewprofile/ViewProfile.css
- webapp/src/pages/viewprofile/ViewProfile.js
- webapp/src/pages/viewprofile/__tests__/ViewProfile.test.js
- webapp/src/pages/viewprofile/components/ViewProfileComponent.js
- webapp/src/pages/viewprofile/index.js
- webapp/src/services/profilelist/profilelist.service.js
Additional info about the application status has been catered for as well
Bootstrap 4.3.1 has been included.
> created a ViewProfile, with readOnly input types.

- api/app/registration/api.py
- webapp/src/pages/offer/components/OfferComponent.js
- webapp/src/services/offer/offer.service.js
> Think this fixes the offer submission bug

- api/app/invitedGuest/api.py
- api/app/invitedGuest/mixins.py
- api/app/invitedGuest/tests.py
- webapp/src/pages/invitedGuests/InvitedGuests.css
- webapp/src/pages/invitedGuests/components/InvitedGuestComponent.js
- webapp/src/services/invitedGuests/invitedGuests.service.js
- webapp/src/utils/validation/validationFields.js
Updated invited guest to take the (minimal set) of additional info required to create a new user in the same UI. This will be a better user experience when adding a lot of invited guests (which we will be doing for 2019!)
> Update Invited Guest 

- webapp/README.md
- webapp/package.json
- webapp/src/pages/viewprofile/components/ViewProfileComponent.js
Removing react-bootstrap from view profile page, because it was causing build issues.
Changes:
- Change from using react-bootstrap `Form` component to normal css `form` component (other changes were done by linter - in future, when code is pushed it will automatically be run through a linter to keep styling consistent and prevent these file changes from been shown by local linters).
> Purged react-bootstrap from view profile page.

- api/app/registration/api.py
> updated the offer email body

- api/app/invitationletter/models.py
- api/migrations/versions/ab8b7ff61eee_.py
> added invitation models

- api/app/registration/models.py
- api/migrations/versions/9630ab6b0437_alter_rejection_reason.py
> Extended rejected_Reason column

- api/app/events/repository.py
- api/app/registration/models.py
- api/app/registrationResponse/api.py
- api/app/registrationResponse/mixins.py
- api/app/registrationResponse/repository.py
- api/app/registrationResponse/tests.py
- api/app/routes.py
- api/app/users/models.py
> Registration admin

- api/app/events/repository.py
- api/app/registration/models.py
- api/app/registrationResponse/api.py
- api/app/registrationResponse/mixins.py
- api/app/registrationResponse/repository.py
- api/app/registrationResponse/tests.py
- api/app/routes.py
- api/app/users/models.py
- webapp/src/App.js
- webapp/src/pages/registrationAdmin/RegistrationAdmin.js
- webapp/src/pages/registrationAdmin/__tests__/RegistrationAdmin.test.js
- webapp/src/pages/registrationAdmin/components/RegistrationAdminComponent.js
- webapp/src/pages/registrationAdmin/index.js
- webapp/src/services/registration/registration.admin.service.js
> Registration admin front end

- api/Dockerfile.deploy
> I'm testing on staging, my apologies

- api/app/routes.py
- api/app/users/api.py
- api/app/users/tests.py
- api/app/utils/errors.py
Haven't run tests locally yet because my Docker is being weird.
> Added emailer

- api/Dockerfile.deploy
Apparently this is the suggested way to do it! 
Let's give it a go
> Updated the environment variables to use default utf

- api/app/invitationletter/generator.py
> properly decode the utf for the mailmerge

- webapp/src/pages/home/Home.js
- webapp/src/pages/registration/Registration.js
- webapp/src/services/invitedGuests/invitedGuests.service.js
- webapp/src/services/registration/registration.service.js
> Updated the home page to show when someone is an invited guest

- api/app/attendance/api.py
- api/app/attendance/tests.py
- api/app/registrationResponse/api.py
> Fixed the accommodation bug

- api/app/attendance/api.py
- api/app/invitedGuest/tests.py
- api/app/registrationResponse/api.py
- api/app/registrationResponse/tests.py
- api/app/users/models.py
- webapp/src/App.js
Added in the registration volunteer role
Fixes #430
> Created the registration-volunteer role

- webapp/src/pages/attendance/Attendance.css
- webapp/src/pages/attendance/components/AttendanceTable.js
Hacky responsiveness attendance page fix.
> Responsiveness for attendance page.

- api/app/responses/api.py
- api/app/responses/tests.py
- api/app/utils/strings.py
Resolves the email ordering in issue #112
> Order questions on application confirmation email

- webapp/src/pages/invitedGuests/components/InvitedGuestComponent.js
Title shows after clicking on the options in the dropdown.
> fixed issue #349

- webapp/src/pages/offer/components/OfferComponent.js
The query looks if any application is submitted and not withdrawn for a particular event ID, and shows the required "you did not apply to attend" message accordingly.
> fixed issue #345

- .circleci/config.yml
> Updated migration to use the google app engine docker

- webapp/src/App.js
Offer page only visible for logged in users.
> fixed issue #469

- api/app/organisation/api.py
- api/app/organisation/models.py
- api/app/registration/api.py
- api/app/responses/tests.py
- api/app/reviews/api.py
- api/app/users/api.py
- api/app/utils/misc.py
- api/app/utils/testing.py
- api/migrations/versions/b2d1fc607635_add_organisation_system_url.py
- webapp/src/pages/home/Home.css
Resolves #511 
Resolves #514 
Resolves #512
> Added system url for organisation, fix logo width

- api/migrations/versions/87213d612eaf_eeml_application_form.py
> EEML Event and Application Form Config

- webapp/src/pages/login/Login.css
- webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js
Issue:
fix screen scaling of smaller devices & fixed styling. 
outcome:
> Reset password screen: button fix & small screen scaling #566

- webapp/public/index.html
- webapp/src/pages/login/components/LoginForm.js
as per issue #517  this should eliminate chrome developer tools warning
> Manifest error #517

- webapp/src/components/ErrorPage.jsx
Removed the Deep Learning Indaba logo and added a note that the bug report email will go to the Baobab team
> Updated error page

- api/app/applicationModel/models.py
- api/app/applicationModel/tests.py
- api/app/events/api.py
- api/app/events/tests.py
- api/app/references/tests.py
- api/app/responses/tests.py
- api/app/reviews/tests.py
- api/app/users/tests.py
- api/migrations/versions/d7f3adff2c9f_.py
Hi All,
This pull request resolves #518 .
I have removed the deadline field from the application form model and updated the code to use application close from event.
> Code Refactor, remove deadline from Application form Model

- webapp/src/App.js
- webapp/src/components/ViewFile.js
> Patching file viewer into production

- api/migrations/versions/02242641e122_add_local_event.py
> Added local event, application form, review form, registration form

- api/app/events/api.py
- api/app/events/tests.py
- webapp/src/pages/home/Home.js
This is the back end changes that need to be made in order to get the event type.
> feat(event_type): Added event_type to event_info return

- webapp/src/pages/invitationLetter/components/Address.js
- webapp/src/pages/invitationLetter/components/InvitationLetterForm.js
- webapp/src/utils/validation/contentHelpers.js
> Remove unused content

- webapp/package-lock.json
- webapp/src/components/form/FormDate.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/pages/invitationLetter/components/InvitationLetterForm.js
- webapp/src/pages/registration/components/GuestRegistrationComponent.js
- webapp/src/pages/registration/components/RegistrationComponent.js
> Add date component

- api/app/references/api.py
- api/app/references/mixins.py
- api/app/references/repository.py
- api/app/references/tests.py
- api/app/utils/errors.py
> added a put to the reference

- webapp/src/pages/applicationForm/components/ApplicationForm.js
Withdraw dialog message into production (requested by EEML)
> Made withdraw message less scary sounding

- CONTRIBUTING.md
- api/glossary_usefulconcepts.md
Hi there !
This is another "tutorial" to help onboarding of new contributors with little experience. Not sure if there are some concepts I completely missed - I would be happy to go add those as well :)
> Glossary backend

- api/migrations/versions/3ec3ed0eb3c6_.py
Fix multiple heads issues in develop
> Added merge migration

- api/app/reviews/api.py
- api/app/reviews/repository.py
- api/app/reviews/tests.py
- api/migrations/versions/6d34d1ab6864_eeml_review_form.py
- webapp/src/App.css
- webapp/src/App.js
- webapp/src/components/User.js
- webapp/src/pages/review/Review.css
- webapp/src/pages/review/components/ReviewForm.js
- webapp/src/pages/reviewAssignment/components/ReviewAssignmentComponent.js
- webapp/src/services/reviews/review.service.js
Added EEML review form and updated review components to make them more generic for multi-tenant support.
Resolves #638
> Eeml review form

- api/app/reviews/api.py
- api/app/reviews/repository.py
- api/app/reviews/tests.py
- webapp/src/App.js
- webapp/src/pages/eventHome/EventHome.js
- webapp/src/pages/reviewHistory/components/ReviewHistoryComponent.js
- webapp/src/pages/reviewHistory/components/tablecolumns.js
Update review history to remove Indaba specific items.
Disable event admin links in nav that don't work.
> Update Review History

- README.md
Hi there!
I just updated the Docker and Windows solution. I also changed one line - not sure if you agree with the wording, but I was thinking the use of "regularly" might help people realise that contributing isn't a once off situation! Happy for it be changed though :)
> feat(README): Update docs to include solution to Windows Home Edition

- api/app/applicationModel/repository.py
- api/app/events/models.py
- api/app/events/tests.py
- api/app/references/tests.py
- api/app/responses/api.py
- api/app/responses/mixins.py
- api/app/responses/models.py
- api/app/responses/repository.py
- api/app/responses/tests.py
- api/app/reviews/tests.py
- api/app/users/models.py
- api/app/users/tests.py
- api/app/utils/errors.py
- api/app/utils/testing.py
Resolves #560 
Note this is merging into branch `applicationFormNomination` and not `develop`
I think I also just want to give this a once over in the morning. It's late so might have missed something.
> Combine nomination branches

- api/app/events/api.py
- api/app/events/models.py
- api/app/events/repository.py
- api/app/events/status.py
- api/app/routes.py
- api/app/users/api.py
- api/app/users/mixins.py
- webapp/src/components/EventStatus.js
- webapp/src/pages/eventHome/EventHome.js
Moved logic to EventStatus
Changed "user for organisation" to "user is event attendee" - will update the App.js accordingly once this is merged.
> Miniconf integration update

- integration-tests/cypress/integration/signup.spec.js
- webapp/src/App.css
- webapp/src/App.js
- webapp/src/components/form/FormTextBox.js
- webapp/src/pages/createAccount/CreateAccount.css
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/pages/eventHome/EventHome.js
- webapp/src/pages/home/Home.css
- webapp/src/pages/home/Home.js
- webapp/src/pages/login/Login.css
- webapp/src/pages/login/components/LoginForm.js
- webapp/src/pages/profile/Profile.css
- webapp/src/pages/profile/components/ProfileForm.js
Linked to issue #677 
- Moved event-specific menu items to its own navbar
- Updated sign up page
- Updated profile page
- Updated home page
> Update UI Design

- webapp/src/App.css
- webapp/src/App.js
- webapp/src/components/User.js
- webapp/src/services/base.service.js
Resolves #718 
i18next already saves the current language in localStorage, so I didn't need to do anything extra there :)
> Added language selector, sending language with all axios requests

- api/app/events/api.py
- api/app/events/models.py
- api/app/events/repository.py
- api/app/events/tests.py
- api/app/utils/testing.py
- api/migrations/versions/4ec21502ae82_add_call_event_type.py
- webapp/public/locales/en/translation.json
- webapp/public/locales/fr/translation.json
- webapp/src/components/EventStatus.js
- webapp/src/pages/home/Home.js
> Call Event Types

- api/app/users/api.py
- api/app/utils/strings.py
- api/migrations/versions/10b4b888c16b_ai4d_first_call_updates.py
- webapp/package.json
- webapp/public/locales/en/translation.json
- webapp/public/locales/fr/translation.json
- webapp/src/App.css
- webapp/src/App.js
- webapp/src/components/form/FormFileUpload.js
- webapp/src/components/form/FormMultiFile.js
- webapp/src/components/form/MultiFileComponent.js
- webapp/src/pages/applicationForm/Application.css
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/pages/createAccount/CreateAccount.css
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/pages/home/Home.js
- webapp/src/pages/login/components/LoginForm.js
- webapp/src/pages/resetPassword/components/RequestPasswordResetForm.js
Partial #768
Resolves #766
Resolves #765
Resolves #764
> Ai4d first call - updates

- webapp/package-lock.json
- webapp/package.json
- webapp/src/pages/createAccount/__tests__/CreateAccount.test.js
- webapp/src/pages/createAccount/components/CreateAccountForm.js
- webapp/src/pages/createAccount/components/PassStrength.js
- webapp/src/pages/createAccount/components/PasswordStrengthBar.js
Loads password strength bar using React Lazy loading.
Fixes #788
> added password strength bar issue #788

- webapp/src/components/answerValue/AnswerValue.js
- webapp/src/components/answerValue/MultiFileValue.js
- webapp/src/components/answerValue/__tests__/AnswerValue.test.js
- webapp/src/components/answerValue/__tests__/MultiFileValue.test.js
- webapp/src/components/answerValue/index.js
- webapp/src/pages/ResponseList/components/ResponseListForm.js
- webapp/src/pages/ResponsePage/ResponsePage.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/pages/review/components/ReviewForm.js
- Add AnswerValue component
- Have MultiFileValue as a standalone component
- Add tests for MultiFileValue and AnswerValue components
Closes #836
> Consolidate answer value display

- api/app/files/api.py
> Add rename parameter to file api

- webapp/src/components/FileUpload.js
- webapp/src/components/ViewFile.js
- webapp/src/components/answerValue/AnswerValue.js
- webapp/src/components/answerValue/MultiFileValue.js
- webapp/src/components/form/FormFileUpload.js
- webapp/src/components/form/MultiFileComponent.js
- webapp/src/pages/ResponsePage/ResponsePage.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
- webapp/src/utils/files.js
> Add rename parameter to file download URLs

- webapp/src/pages/review/components/ReviewForm.js
> Review sections front-end

- api/app/reviews/api.py
- api/requirements.txt
- webapp/src/pages/reviewDashboard/components/ReviewDashboard.js
> Review dashboard

- api/app/responses/api.py
- webapp/src/pages/ResponseList/components/ResponseListForm.js
Updated the admin response list page with an email column and user/email filtering. 
resolves #1040
> Issue #1040: Response List Page UI Updates

- webapp/src/pages/ResponseList/components/ResponseListComponent.js
- webapp/src/pages/ResponsePage/ResponsePage.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
Reverts deep-learning-indaba/Baobab#1192
> Revert "Release dependency changes"

- webapp/src/pages/ResponseList/components/ResponseListComponent.js
- webapp/src/pages/ResponsePage/ResponsePage.js
- webapp/src/pages/applicationForm/components/ApplicationForm.js
Reverts deep-learning-indaba/Baobab#1191
> Revert "Simplified dependencies in application form, filtering response page"

- webapp/src/pages/createApplicationForm/components/Question.js
validation for option values being unique in for editor
> Add validation for option values being unique in form editor

- webapp/src/components/EventStatus.js
- webapp/src/pages/ResponseList/components/ResponseListComponent.js
- webapp/src/pages/ResponsePage/ResponsePage.js
- webapp/src/pages/review/components/ReviewForm.js
- Fix minor bugs 
-Displaying sections in responsePage
> Display all review sections in responsePage - issue-1294

- webapp/src/pages/reviewForm/components/ReviewForm.js
Given that there is no review_close date(null) for event journal (deadline) that produce (error r-xx where xx-number) 
We have just fixed a date when we encounter this case
> fixing error review deadline for journal
